import "server-only"

import snapshot from "@/data/up-snapshot.json"
import type {UpCollection} from "./client"
import type {UpTransaction} from "./types"

/**
 * Thirteen months of history, frozen at build time.
 *
 * Settled transactions don't change, so walking fifty pages of them on every
 * cold render was work being done at the wrong moment — about 47 seconds of
 * it, against a 60-second serverless ceiling. Built once, the same history
 * costs a render nothing at all.
 *
 * What it can't do is tell you anything current, which is why balances and
 * saver positions still go to the network on every load. The trade is
 * explicit: the past is bundled, the present is fetched.
 *
 * The file is generated by `pnpm snapshot` and is not in the repository. When
 * it's empty — a clone, or a build with no token — this returns null and the
 * caller falls back to fetching live.
 */

type Snapshot = {
  generatedAt: string | null
  since: string | null
  count: number
  truncated: boolean
  transactions: UpTransaction[]
}

// The JSON is data, not a type: TypeScript infers a structural type from
// whatever happened to be in the file when it was generated, which is both
// enormous and wrong in the details (every string literal widened, absent
// nullable fields inferred as null). The shape is guaranteed by the script
// that writes it, so it's asserted here once.
const data = snapshot as unknown as Snapshot

/** When the bundled history was taken, or null when there isn't any. */
export function snapshotTakenAt(): string | null {
  return data.transactions.length === 0 ? null : data.generatedAt
}

/**
 * The bundled history, or null when it can't answer the question asked.
 *
 * A snapshot that starts later than the caller's window is worse than no
 * snapshot: it would silently shorten the averaging window and understate
 * every figure built on it. So it's all or nothing.
 */
export function snapshotSince(sinceIso: string): UpCollection<UpTransaction> | null {
  if (data.transactions.length === 0 || data.since === null) return null

  const wanted = Date.parse(sinceIso)
  const covered = Date.parse(data.since)
  if (!Number.isFinite(wanted) || !Number.isFinite(covered)) return null
  // A minute of slack: the snapshot and the render compute the same month
  // boundary, but not at the same instant.
  if (covered > wanted + 60_000) return null

  return {items: data.transactions, truncated: data.truncated}
}
